// <auto-generated />
namespace Budget.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ItemSubValor2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemSubValor2));
        
        string IMigrationMetadata.Id
        {
            get { return "201501201258199_ItemSubValor2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
